
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: deluge-pv
# spec:
#   capacity:
#     storage: 2Gi
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: local-storage
#   local:
#     path: /mnt/media/config/deluge
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - node3
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 
  storageClassName: nfs-client