apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share # The name of your persistent volume.
  labels:
    storage: nfs # The labels used when matching with a Persistent Volume Claim.
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.4.38 # The FQDN server name or IP of the NFS server goes here.
    path: /mnt/nfs_shares/media # The path to your NFS server volume.