apiVersion: v1
kind: Secret
metadata:
    name: drone-secret
#create with openssl rand -hex 16 | base64
data:
    DRONE_RPC_SECRET: 
stringData:
    DRONE_GITEA_CLIENT_ID: 
    DRONE_GITEA_CLIENT_SECRET: 
   