apiVersion: v1
kind: Secret
metadata:
    name: elastic-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:8jqHYfOqEMGX4Qyor0Aeu6kCvXCFh+q9,iv:Vf36QJ0tDpAnS/ph9uWDcEwT2p3ZlgQL8w5XdNLlDpQ=,tag:xwRv9x/KPnian44c9GGbzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lygag0cr3dp69mlmhs4agv2lztxcha3t4smwsd6fujdeemacrdxs79xac0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dkUydXV4bDRnVllsU090
            ZExTemFIZTRMRjl1SCs4cjFkTlZybGdTU2dRCi8xdlZWTG42V0dLeTlRYzNySlZX
            THRhZUpNMU9kTHk5eDRDbkNCWEpRNGcKLS0tIG9PaDJXNk9Ra1lBRnJ5ZVpPbXU1
            cXVaK3ViRUNaMlZRVHBlTUxJSTU0VmcK0JNeAW8XcTI5POVdXmaN29K/s1PkBqZ8
            OeNB0BXabmUtEBMHjHvqveRRnLMQxeHsFHX6p0HKOMhGzkbz5ZaTtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-23T18:20:40Z"
    mac: ENC[AES256_GCM,data:umaFPHk1fxAeCpklM+FAm0lhfPFAG/bYr7nip0jMsxakpHBLUTFW4Lm7czkIUBPtuu5LkUfoHGbNGwRclTuR58DpnGL1asoiQV/xthJMcd+b9oLeC52vOj2thZwFkdqud3F8LEMYh/5tglcyPCA3MSskYURP3UWPyMKdwJfO2Ag=,iv:nW7rzKWDAGnm85SrnE1n3toGghQYSKNkkrys3VmUePc=,tag:LPx+6ZLOCG0J5szyAeSpYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
