namespace: nfs-provisioner

bases:
  - github.com/kubernetes-sigs/nfs-subdir-external-provisioner//deploy
resources:
- ../../../../configs/instance-namespaces/default-namespace

patchesStrategicMerge:
  - patch-nfs-details.yaml

patches:
  - target: 
      kind: Namespace
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: nfs-provisioner

