apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: patch-operator
  namespace: operators
spec:
  interval: 1h
  url: https://redhat-cop.github.io/patch-operator
  timeout: 15m