apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:8fl/4uL6lDwixwvFqnlrRr73qtQMptyxSwTPik6fij8puaEYTYSkqA==,iv:inSaVcPFoLKbVtNyoQqKQMFy9GN8RNfO3DCyC64TQuk=,tag:7oE7KzWDYiJxqWnUiE6DHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lygag0cr3dp69mlmhs4agv2lztxcha3t4smwsd6fujdeemacrdxs79xac0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dkUydXV4bDRnVllsU090
            ZExTemFIZTRMRjl1SCs4cjFkTlZybGdTU2dRCi8xdlZWTG42V0dLeTlRYzNySlZX
            THRhZUpNMU9kTHk5eDRDbkNCWEpRNGcKLS0tIG9PaDJXNk9Ra1lBRnJ5ZVpPbXU1
            cXVaK3ViRUNaMlZRVHBlTUxJSTU0VmcK0JNeAW8XcTI5POVdXmaN29K/s1PkBqZ8
            OeNB0BXabmUtEBMHjHvqveRRnLMQxeHsFHX6p0HKOMhGzkbz5ZaTtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-23T21:27:37Z"
    mac: ENC[AES256_GCM,data:2umEVa8k6Bgm9jwxBd2PoDCWqtvPydgKi6WvDD0VpHSu61YZ7NTXfN/Jt8uBMcGEPLG6keaC2f3k1CY8F+jiNt9rCqYFddPPW/D3c3F03xXykTvtB3StkT6l9aF0IxxxQp/FoTOrdDOUUrD9Gb1+PBnC9pScakbxsNYGSeP5QP0=,iv:0YuQnEUnw3NxInoGFMhQkZj635SDJIpAeKS/Nk/qO0Q=,tag:arUEpBbCAn0HoRv/6UipNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
