apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-demo

generators:
  - secret-generator.yaml

resources:
  - ./tasks
  - trigger.yaml
  - service-account.yaml
  - event-listener.yaml
  - ingress.yaml
  - pipeline.yaml
  - trigger-binding.yaml
  - trigger-template.yaml
  - webhook.yaml
  - ../../../../configs/instance-namespaces/default-namespace

patches:
  - target: 
      kind: Namespace
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: tekton-demo
    