apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: cert-manager
spec:
  secretName: wildcard-certificate-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: '*.${CLUSTER_DOMAIN}'
  dnsNames:
  - '*.${CLUSTER_DOMAIN}'