apiVersion: v1
kind: Secret
metadata:
    name: sendgrid-api-token-secret
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:mmrgtG7SGtH8d+fFV82UqnUW6+i6WbrI1gvkkCdvDWap81wSHkTAusgrtU4R0oREk9+JHY5Co4cQQXDtyJcJ1+1oJi3X,iv:Gabv+2t7th9goGtrJSg/RYmhI5ZrefCaUBruuX3TCfU=,tag:zxsT0KLGApuH9d0fsLohJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lygag0cr3dp69mlmhs4agv2lztxcha3t4smwsd6fujdeemacrdxs79xac0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dkUydXV4bDRnVllsU090
            ZExTemFIZTRMRjl1SCs4cjFkTlZybGdTU2dRCi8xdlZWTG42V0dLeTlRYzNySlZX
            THRhZUpNMU9kTHk5eDRDbkNCWEpRNGcKLS0tIG9PaDJXNk9Ra1lBRnJ5ZVpPbXU1
            cXVaK3ViRUNaMlZRVHBlTUxJSTU0VmcK0JNeAW8XcTI5POVdXmaN29K/s1PkBqZ8
            OeNB0BXabmUtEBMHjHvqveRRnLMQxeHsFHX6p0HKOMhGzkbz5ZaTtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T03:50:53Z"
    mac: ENC[AES256_GCM,data:qj+PLeET7JJTbSdJqWn51Bi+0S3m0eYCd1X73opjpCx+9V6GFYmjaGr11HQyA89wtM3pHZGrepDRQSHsfLa/jE4HOXuCyg/AbbNZbGGStBbiAtLntGeYh9w2ZcZiKGmOEXU9hNVBskcvDb2m0TbEvaf8RIgN+c3aBbKgH/ug9iQ=,iv:1twQMlBqKCjBn9ycrYhXa6YSjy7T9x9+laCbbPwJcQU=,tag:RUa9usRzDYVIjmAvhyBcUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
