apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  image: docker.${CLUSTER_DOMAIN}/awx/awx
  image_version: 22.4.1.dev0
  ee_images:
    - name: "awx custom"
      image: "docker.${CLUSTER_DOMAIN}/awx/awx-ee:latest"


  service_type: clusterip
  secret_key_secret: awx-secret-key
  admin_email: ${EMAIL}
  admin_user: admin

  # ingress_annotations: |
  #   hajimari.io/appName: awx
  #   hajimari.io/enable: "true"
  #   kubernetes.io/ingress.class: nginx
  #   cert-manager.io/cluster-issuer: letsencrypt-issuer
  # ingress_tls_secret: awx-certificate-tls
  # hostname: awx.${CLUSTER_DOMAIN}
  # ingress_path: "/"
  # ingress_path_type: Prefix

  
  postgres_resource_requirements:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: '1'
      memory: 2Gi
  postgres_storage_requirements:
    requests:
      storage: 8Gi
    limits:
      storage: 50Gi
  postgres_storage_class: nfs-client
  postgres_extra_args:
    - '-c'
    - 'max_connections=1000'
