apiVersion: v1
kind: Secret
stringData:
    secret_key: ENC[AES256_GCM,data:F5HVq94lF3vkQN2Vw2SbuyvbIW5O5so2KQTSOsBgo5s=,iv:/jQGp2Gga2p+Ov+I3sE9kei7b262i2/OnweCOvijkGA=,tag:EEh397ST3B8W3n/IPJA9QA==,type:str]
metadata:
    name: awx-secret-key
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lygag0cr3dp69mlmhs4agv2lztxcha3t4smwsd6fujdeemacrdxs79xac0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNklocXJZenExSUt4Q1NG
            ajc2T0t6VEZWbHlRUmNFSXN5Y0RUSDF4bFRNCjhGODdGaGM4dHo2cFc1S21YcDhD
            MHhTTzVsSjEzeDUzNUJnSGdNelViOWsKLS0tIFVORVNoV0ZKUkYzWjhHcWZtdklQ
            L0oxYXNLU3kwSWRqeURBYkowemQ0SE0K9mPGmBdb4L/c/Cc7DdUZpzGJjeC0RGYG
            IdsHX7lQP2IH0oz9UJELwP7wfyvp0t8otwST4y+lI19hphn9IoDIEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T14:24:58Z"
    mac: ENC[AES256_GCM,data:/mDOgL3UutPJl/tdxKdXsrwHVD7f7FNiAwuzbDzQR+eG+KSUAcDn/KazRHw4sEHzTr779i1FZdD/z7p7DmpI2j3cDauRC0Nqn7vY6J05TM98VL9quxcqO8WEOT6Xf6NpclAFRAFwGZdSK7a+8Mz7xYS4/+ffLYjQbnrPvGQua4E=,iv:VeOW4hsAmtkt5/ch0lanBOkMLr2qwID+PmH2SL415PY=,tag:aEeOM5+9CJpsmF+dfLn4Gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
