apiVersion: operators.coreos.com/v1alpha1 
kind: Subscription 
metadata: 
  name: my-flux 
  namespace: operators 
spec: 
  channel: stable 
  name: flux 
  source: operatorhubio-catalog 
  sourceNamespace: olm