apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.8.1
  nodeSets:
  - name: default
    config:
      node.store.allow_mmap: false
    count: 2
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        storageClassName: nfs-client
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              memory: 2Gi
