
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: manual
# provisioner: kubernetes.io/no-provisioner

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data # The name of your persistent volume.
  labels:
    storage: elasticsearch-data # The labels used when matching with a Persistent Volume Claim.
spec:
 # storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.4.38 # The FQDN server name or IP of the NFS server goes here.
    path: /mnt/nfs_shares/elasticsearch # The path to your NFS server volume.
    readOnly: false
