apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: components
  namespace: argocd
spec:
  interval: 10m0s
  dependsOn:
    - name: core
  sourceRef:
    kind: GitRepository
    name: home-repo
  path: ./components
  prune: true
  validation: client
  # healthChecks:
  #   - apiVersion: helm.toolkit.fluxcd.io/v1beta1
  #     kind: HelmRelease
  #     name: podinfo
  #     namespace: podinfo
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: ConfigMap
      name: global-settings
    - kind: Secret
      name: global-secrets
    - kind: ConfigMap
      name: cluster-settings
    - kind: Secret
      name: cluster-secrets
