apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.7.5
  valuesFile: values.yaml
  namespace: ingress-nginx
  releaseName: ingress-nginx

resources:
  - ../../../../configs/instance-namespaces/default-namespace
# #- ingresses/dashboard.yaml
# #- https://github.com/kubernetes/ingress-nginx/tree/main/deploy/static/provider/baremetal/deploy.yaml
# - ingress.yaml


patches:
  - target: 
      kind: Namespace
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: ingress-nginx

#resources:
#- instance-namespace.yaml
#- cluster-cert-manager.yaml
#- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.5.1/deploy/static/provider/cloud/deploy.yaml
#- ingress-deployment.yaml
