apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
#  - ../../../../settings/env-vars/base
  - ../../secrets/cloudflare-api-token
  - ../../../configs/instance-namespaces/default-namespace
  # - qbittorrent
  - lidarr
  - deluge
  - prowlarr
  - radarr
  - readarr
  - base
  - sonarr
  # - vnc


patches:
  - target: 
      kind: Namespace
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: media
    